server:
   port: 8761
spring:
   application:
      name: SERVICE-REGISTRY
   cloud:
      config:
         enabled: false   
eureka:
   instance:
      hostname: localhost
   client:
      register-with-eureka: false
      fetch-registry: false   
