server:
  port: 8761
spring:
  application:
    name: SERVICE-REGISTRY
  cloud:
    config:
      enabled: false   
eureka:
  instance:
    hostname: "eureka-0.eureka"
  client:
    register-with-eureka: false
    fetch-registry: false   
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
